# Site settings
title: "[ACME]"
description: "ACME oneM2M CSE"
url: "https://ankraft.github.io/"
author:
  name: "Andreas Kraft"
#email: xxx@example.com
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: ""
github_username:  ""

# Build settings
markdown: kramdown
source: .
destination: ./_site
permalink: /:year/:month/:title.html
paginate: 8
paginate_path: /page:num/

excerpt_separator: <!--more-->

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
navigation_menu: false
theme: minima
